## 数据源配置
spring:
  datasource:
#    url: jdbc:mysql://localhost:8066/mydb?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://192.168.1.102:3306/mydb0?useUnicode=true&characterEncoding=utf8
    username: root
#    password: 123456
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
## Mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
